#! /bin/sh
sxhkd &
picom -b --animations --animation-window-mass 0.3 --animation-for-open-window zoom --animation-stiffness 400 &
feh --bg-scale ~/Wallpapers/od_bspwm.png
setxkbmap -layout us,ru -option grp:win_space_toggle
flameshot &
~/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 
bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
